
version: '3'

services:

  app:
    build:
      context: node
    # image: edsonkoguishi/node-mysql
    container_name: app
    networks:
      - node-network
    # volumes:
    #   - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    # command: sh -c './wait-for db:5432 -- node index.js'
    depends_on:
      - db

  db:
    # image: mysql:5.7.16
    # image: edsonkoguishi/mysql
    build:
      context: mysql
    # command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    environment:
      # - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  proxy:
    restart: unless-stopped
    image: nginx
    container_name: proxy
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network      

networks:
  node-network:
    name: node-network
    driver: bridge