
version: '3'

services:

  db:
    # image: mysql:5.7.16
    # image: edsonkoguishi/mysql
    build:
      context: mysql
    # command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network

  app:
    # image: edsonkoguishi/node-mysql
    build:
      context: node
    container_name: app
    networks:
      - node-network
    # volumes:
    #   - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    depends_on:
      - db

  proxy:
    # image: nginx
    build:
      context: nginx
    container_name: proxy
    restart: unless-stopped
    networks:
      - node-network      
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  node-network:
    name: node-network
    driver: bridge