FROM node:15

RUN apt update && \
    apt install -y wget netcat && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

WORKDIR /usr/src/app

RUN npm init -y
RUN npm install mysql2 -y
RUN npm install express --save

COPY ./index.js .
# instalar pacotes através do RUN APT-GET

EXPOSE 3000

CMD ["node", "index.js"]
